Aboutus style #10
facg3/Elegant-Project pull request #53
Opened 2018-01-15 16:43 UTC by walaamedhat

- fixes #10  

- related to #10   

- make aboutus page html,css

2018-01-16 22:42 UTC, muhmushtaha requested changes

2018-01-16 22:42 UTC, muhmushtaha commented on public/css/login.css
> +body {
we have a branch for login which has the login files, why we have login files here ?

2018-01-16 22:42 UTC, muhmushtaha commented on public/aboutus.html
> +      <center><div class="parag"><p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an un
we shouldn't use center tag anymore!
and in the small screen the text should be wrapped

2018-01-17 07:42 UTC, Salam-Dalloul commented on public/aboutus.html
> +    <div class="burgerButton">
i think it would be better if you use font awesome for this :smile:

2018-01-17 07:45 UTC, Salam-Dalloul commented on public/css/aboutus.css
> +  justify-content: space-around;
you have to use one property for justify content :smile_cat:

2018-01-17 07:46 UTC, Salam-Dalloul commented on public/css/aboutus.css
> +footer {
you should use classes, it would be better :D

2018-01-17 07:47 UTC, Salam-Dalloul requested changes
check these :smiling_imp:

2018-01-17 08:21 UTC, closed without merging