About Us style #10
facg3/Elegant-Project pull request #61
Opened 2018-01-16 08:48 UTC by walaamedhat

- fixes #10  

- related to #10   

- make aboutus page responsive

2018-01-17 07:58 UTC, MahmoudMH commented on public/aboutus.html
> +      <center><div class="parag"><p class="p">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
you should don't use tag center anymore as mush said you. 
div ! why you use it ? you can put it inside !.. so we can discuss it if any problem

2018-01-17 10:50 UTC, muhmushtaha requested changes
- the text takes a width more than the parent in small screens
- fix the conflicts @walaamedhat

2018-01-17 11:34 UTC, walaamedhat commented
changes done

2018-01-17 15:07 UTC, muhmushtaha commented
pull from the master on this branch and fix the conflicts
@walaamedhat

2018-01-17 17:11 UTC, Salam-Dalloul submitted a review, later dismissed

2018-01-19 11:09 UTC, muhmushtaha approved these changes

2018-01-19 11:09 UTC, muhmushtaha commented on public/aboutus.html
> +    <center>
center tag again?

2018-01-19 11:09 UTC, merged