Final resposive men and women saved
facg3/Elegant-Project pull request #66
Opened 2018-01-16 12:35 UTC by Salam-Dalloul

responsive design for 
menFashion
womenFashion
menOutfits
womenOutfits
saved

2018-01-17 10:39 UTC, muhmushtaha requested changes
- the way of displaying the items not responsive in all pages 
- men outfits display the items in one column 
@Salam-Dalloul

2018-01-17 11:29 UTC, MahmoudMH submitted a review, later dismissed

2018-01-17 13:45 UTC, muhmushtaha commented
fix the conflicts 
@Salam-Dalloul

2018-01-17 15:06 UTC, muhmushtaha commented
pull from the master on this branch and fix the conflicts
@Salam-Dalloul

2018-01-18 07:48 UTC, muhmushtaha approved these changes

2018-01-18 07:48 UTC, merged