Men outfits
facg3/Elegant-Project pull request #83
Opened 2018-01-19 14:52 UTC by Salam-Dalloul

### Fixes
fixes #<24>

### Related
related to #<issue_number>

### Summary
upload outfits from database
### Major Changes
[**OPTIONAL for small PRs**] Detailed description of major changes in the PR, ideally with references to relevant commits, issues, line-numbers, etc.

2018-01-20 23:16 UTC, walaamedhat reviewed
just write the number of issue you''re fixed it right here and in the last 2 pull request :+1:

2018-01-20 23:21 UTC, walaamedhat submitted a review, later dismissed

2018-01-20 23:21 UTC, walaamedhat commented on public/js/womenFashion.js
> +function btnClick() {
you can write this function in one file and use it any where you want

2018-01-21 11:36 UTC, muhmushtaha submitted a review, later dismissed
we don't have the outfits table, how you did the route?
plz, test the routes before pushing.

2018-01-21 11:37 UTC, muhmushtaha requested changes
we don't have the outfits table, how you did the route?
plz, test the routes before pushing.

2018-01-21 19:34 UTC, Ghadeer93 approved these changes

2018-01-21 19:34 UTC, merged