hbs Contactus form and aboutus #35
facg3/Elegant-Project pull request #87
Opened 2018-01-21 06:17 UTC by walaamedhat

### Fixes
fixes #35

### Related
related to #35 

### Summary
convert contact us and about us to hbs and make routs

2018-01-21 07:02 UTC, Salam-Dalloul submitted a review, later dismissed

2018-01-21 11:56 UTC, muhmushtaha requested changes
- the content is not centered  vertically
- the header buttons need more style in the about us page

2018-01-22 08:21 UTC, MahmoudMH submitted a review, later dismissed

2018-01-22 09:12 UTC, muhmushtaha approved these changes

2018-01-22 09:13 UTC, merged