logout #89
facg3/Elegant-Project pull request #90
Opened 2018-01-21 06:53 UTC by walaamedhat

### Fixes
fixes #89 

### Related
related to #89 

### Summary
make a routs for logout and function logout

2018-01-21 06:57 UTC, Salam-Dalloul submitted a review, later dismissed

2018-01-21 12:00 UTC, Ghadeer93 commented
@walaamedhat  :smile:  , solve your Conflicting files and push it again

2018-01-21 12:01 UTC, Ghadeer93 requested changes
solve Conflicting files

2018-01-22 08:16 UTC, MahmoudMH submitted a review, later dismissed

2018-01-22 08:20 UTC, Ghadeer93 approved these changes

2018-01-22 08:20 UTC, merged