Home hbs
facg3/Elegant-Project pull request #91
Opened 2018-01-21 07:54 UTC by MahmoudMH

### Fixes
#32 
### Related
#5 
### Summary
convert home.html to home.hbs with edit's on the header

2018-01-21 12:02 UTC, Ghadeer93 commented
@MahmoudMH   :smile: , solve your Conflicting files and push it again

2018-01-21 12:03 UTC, Ghadeer93 requested changes
solve Conflicting files

2018-01-21 12:50 UTC, MahmoudMH commented
@Ghadeer93 i resolved it _^

2018-01-21 18:29 UTC, Salam-Dalloul submitted a review, later dismissed

2018-01-22 08:15 UTC, Ghadeer93 approved these changes

2018-01-22 08:15 UTC, merged